FROM --platform=${TARGETPLATFORM} jc21/alpine-nginx-full:BASE_TAG
LABEL maintainer="Jamie Curnow <jc@jc21.com>"

RUN apk update \
	&& apk add --update gcc g++ musl-dev make build-base git npm nodejs-current yarn \
	&& rm -rf /var/cache/apk/*
