FROM --platform=${TARGETPLATFORM:-linux/amd64} jc21/alpine-nginx-full:latest
LABEL maintainer="Jamie Curnow <jc@jc21.com>"

ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN apk update \
	&& apk add --update gcc g++ musl-dev make build-base git npm nodejs-current yarn \
	&& rm -rf /var/cache/apk/*
