#!/bin/bash -e

CYAN='\E[1;36m'
YELLOW='\E[1;33m'
RESET='\E[0m'

echo -e "${CYAN}Building docker multiarch: ${YELLOW}${*}${RESET}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.."

# Buildx Builder
docker buildx create --name alpine-nginx-full || echo
docker buildx use alpine-nginx-full

docker buildx build \
	--platform linux/amd64,linux/arm64,linux/arm/7 \
	--progress plain \
	--pull \
	$@ \
	.

echo -e "${CYAN}Multiarch build completed${RESET}"
