#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building golang ${YELLOW}${GO_VERSION}...${RESET}"

apk add --no-cache --virtual .build-deps go
wget -O go.tgz "https://dl.google.com/go/go${GO_VERSION}.src.tar.gz"
tar -C /usr/local -xzf go.tgz
rm -rf go.tgz
cd /usr/local/go/src/
./make.bash

export PATH="/usr/local/go/bin:$PATH"
export GOPATH=/opt/go/
export PATH=$PATH:$GOPATH/bin

apk del .build-deps

echo -e "${BLUE}$(go version)"
echo -e "${BLUE}❯ ${GREEN}Golang build completed${RESET}"

echo -e "${BLUE}❯ ${CYAN}Installing golang deps...${RESET}"

# Gotools
if [ "$TARGETPLATFORM" == "" ] || [ "$TARGETPLATFORM" == "linux/amd64" ]; then
	cd /usr
	wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0
fi

go get -u github.com/kyoh86/richgo

echo -e "${BLUE}❯ ${GREEN}Golang deps completed${RESET}"