#!/bin/bash -e

CYAN='\E[1;36m'
YELLOW='\E[1;33m'
RESET='\E[0m'

echo -e "${CYAN}Installing nginx: ${YELLOW}${*}${RESET}"

cd /tmp/nginx
make install \
rm -rf /tmp/nginx

echo -e "${CYAN}Nginx install completed${RESET}"
